### ISSUE TITLE
categorical update problem when l=u

### ISSUE THREAD

**Issue by haiyanyin** [floringogianu/categorical-dqn#1]
In def _get_categorical(self, next_states, rewards, mask),
when "b" happens to be an integer (e.g., bellman_op clamped to be self.v_max, so b=51), 
the floor and ceil indexe values, "l" and "u" will be equal.
This seems to cause trouble to the distribution projection, as the category "b" will be projected to nowhere.

**Comment by Kaixhin** [comment]
Interesting. Presumably one has to tune `v_min` and `v_max` to a suitable range, but did this occur with this code on an Atari game with reward clipping? If so then yes there'll need to be some additional checks in place.

**Comment by floringogianu** [comment]
@haiyanyin thank you for spotting this issue. @Kaixhin thanks for fixing it.
