### ISSUE TITLE
Excessive clamping

### ISSUE THREAD

**Issue by Kaixhin** [floringogianu/categorical-dqn#3]
It seems like the [clamping of the network's output in the update](https://github.com/floringogianu/categorical-dqn/blob/master/policy_improvement/categorical_update.py#L53) is a bit excessive? Given values of x in [0, 1] (valid probabilities), as x -> 0, log(x) -> -infinity, so clamping the minimum value makes sense, but log(1) = 0, so there's no issues with the max value. Pinging @tudor-berariu as well.

Empirically, this might be an issue. I'm running my Rainbow agent with a minimum clamp of 0.001 (arbitrarily chosen), and get the following rewards and Q-values on Space Invaders (the Q-values are in line with what is reported in the Double DQN paper; unfortunately I do not have reported Q-values for Rainbow):
![newplot](https://user-images.githubusercontent.com/991891/38400432-09bf6dec-391e-11e8-879e-dc6957050259.png)
![newplot 1](https://user-images.githubusercontent.com/991891/38400435-0c353e4e-391e-11e8-9a1a-6a2ab4a23765.png)

Whereas when I use a minimum clamp of 0.01 and maximum clamp of 0.99 as in this repo, I get the following, which indicates that this prevents the network from accurately estimating Q (note that this is the first time I've ever seen Q-values so far from what I got above, so the issue clearly lies with the clamping):
![newplot 2](https://user-images.githubusercontent.com/991891/38400513-53460d36-391e-11e8-9abb-12e2dcf3d280.png)
![newplot 3](https://user-images.githubusercontent.com/991891/38400515-55c57920-391e-11e8-9226-923512b1c88b.png)

**Comment by floringogianu** [comment]
Really nice issue report, thanks for opening it. I would never have assumed this to be a problem. Let me know if you want to open a pull request for this one too. Incidentally I am back working on RL these days so I will check it out on _Space Invaders_ too.

**Comment by Kaixhin** [comment]
I can send in a PR but first I'd like to see if Tudor has any more insights on this.

**Comment by tudor-berariu** [comment]
I don't. Your observation is correct. There seems to be no reason for the maximum clamp. Although I am surprised by the gravity of that decision in your experiments.

**Comment by Kaixhin** [comment]
Update: I now suspect that clamping at all, despite the potential problems, is detrimental. Comparing two ongoing runs, the top having a lower minimum clamp of 1e-5 and the bottom having no clamping at all, it seems to indicate that clamping should be removed altogether.

Minimum clamp = 1e-5:
![newplot 3](https://user-images.githubusercontent.com/991891/39412290-070d316a-4be8-11e8-849e-4a69054f8275.png)
![newplot 2](https://user-images.githubusercontent.com/991891/39412292-0a43fe5e-4be8-11e8-8163-34e36fdd097f.png)

No minimum clamp:
![newplot 1](https://user-images.githubusercontent.com/991891/39412294-10e55b72-4be8-11e8-8735-d74ad207e37d.png)
![newplot](https://user-images.githubusercontent.com/991891/39412296-14132374-4be8-11e8-800a-da238535f6f8.png)
